### ISSUE TITLE
Website certificate error

### ISSUE THREAD

**Issue by acgrobman** [g-rocket/5cMenuFetcher#1]
The website isn't working on mobile due to a certificate error.

On PC, the following error appears:
![image](https://user-images.githubusercontent.com/25434173/35190497-0fe42bfe-fe18-11e7-8fff-d8f5d3541e73.png)

**Comment by g-rocket** [comment]
Thanks for letting me know!  Should be fixed now.  I was having some trouble getting letsencrypt to work after they [disabled the challenge I've been using](https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188) but it's good now.
